spring:
  datasource:
    url: jdbc:h2:mem:app_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      new_generator_mappings: false
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  jackson:
    default-property-inclusion: non_null
---